//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_Tarasov
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public int id_order { get; set; }
        public string articul { get; set; }
        public int count { get; set; }
        public System.DateTime date_order { get; set; }
        public System.DateTime date_vidachi { get; set; }
        public Nullable<int> id_punkt { get; set; }
        public string fio_client { get; set; }
        public int code { get; set; }
        public bool status { get; set; }
    }
}
