//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_Tarasov
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string articul { get; set; }
        public int Price { get; set; }
        public int dscount_max { get; set; }
        public string proizvod { get; set; }
        public string postav { get; set; }
        public int discont { get; set; }
        public int count { get; set; }
        public string dictionary { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> id_category { get; set; }
        public string name { get; set; }
    }
}
