//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_Tarasov
{
    using System;
    using System.Collections.Generic;
    
    public partial class punkt
    {
        public int id { get; set; }
        public int index { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int Number_house { get; set; }
    }
}
